### ISSUE TITLE
Permission to include in thesis

### ISSUE THREAD

**Issue by oxinabox** [JuliaText/Embeddings.jl#17]
@dellison 
looks like the JOSS paper is proceeding.

I have wish to include the version that is currently under review in my thesis, as an appendix.
(Software developed during PhD candidature).

For me to be allowed to do that,
I need your permission to include it,
and agreement that my contributions are correctly summarized as:

 > Original and primary author of software. Wrote publication.

If you agree, can you send me an image of your signature (ideally a SVG or something).
If you are not happy with the idea of just sticking it somewhere public like git,
can you email it to me at lyndon.white@research.uwa.edu.au ?

**Comment by oxinabox** [comment]
Don't forget. :-)

**Comment by oxinabox** [comment]
@dellison  can you do this ASAP?

**Comment by dellison** [comment]
Whoops, I'm very sorry for the delay! I just sent it you via email.

**Comment by oxinabox** [comment]
thanks
