### ISSUE TITLE
doc links in README are broken

### ISSUE THREAD

**Issue by ssfrr** [JuliaText/Embeddings.jl#18]
They currently link to https://juliatext.github.io/Embeddings.jl/stable and https://juliatext.github.io/Embeddings.jl/latest, neither of which return 404.

**Comment by oxinabox** [comment]
Yes, they really shouldn't  be there.
Left over from the template.
The docs are all in the readme.
I don't think this package is complex enough for "real" docs.

**Comment by oxinabox** [comment]
Fixed by removing docs link
