### ISSUE TITLE
FastText embeddings for unseen words

### ISSUE THREAD

**Issue by Jakobhenningjensen** [JuliaText/Embeddings.jl#41]
One of the strengths of FastText is that it (unlike Word2Vec) can create embeddings for new/unseen words.

Am I mistaken when this is not doable in this implementation since we use the index of a given word to get the embeddings

```julia
using Embeddings
const embtable = load_embeddings(Word2Vec) # or load_embeddings(FastText_Text) or ...

const get_word_index = Dict(word=>ii for (ii,word) in enumerate(embtable.vocab))

function get_embedding(word)
    ind = get_word_index[word]
    emb = embtable.embeddings[:,ind]
    return emb
end
```

**Comment by oxinabox** [comment]
Yes, we don't have a full FastText implementation here.
Just a lookup table from the predefined word lists
